SKILLS = [
    "python",
    "java",
    "c++",
    "javascript",
    "react",
    "nodejs",
    "mongodb",
    "mysql",
    "html",
    "css",
    "tailwind",
    "docker",
    "kubernetes",
    "aws",
    "git",
    "github",
    "rest api",
    "fastapi",
    "flask",
    "django",
    "machine learning",
    "data structures",
    "algorithms"
]